version: '3.8'
services:
  mysql:
    image: mysql:latest
    container_name: my-mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: theharsh@230510
      MYSQL_DATABASE: springboot_db
    ports:
      - "3306:3306"
    networks:
      - my-network

  springboot-app:
    build: .
    container_name: my-springboot-api
    restart: always
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/springboot_db?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: theharsh@230510
    ports:
      - "8080:8080"
    networks:
      - my-network

networks:
  my-network:
